name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set node version
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install pnpm and version
        uses: pnpm/action-setup@v2
        with:
          version: 7.27.0

      - name: Install dependencies
        run: pnpm install

      - name: Generate static files
        run: pnpm generate

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "2030"
          entrypoint: "https://deno.land/std@0.178.0/http/file_server.ts"
          root: ".output/public"
